# version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: supabase_postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3522:3522"
    container_name: connectix_backend
    env_file:
      - backend/config/.env
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    volumes:
      - ./backend:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3232:3232"
    container_name: connectix_frontend
    volumes:
      - ./frontend:/usr/src/app:cached
      - react_node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    tty: true

networks:
  app-network:
 
volumes:
  db-data:
  react_node_modules: